# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: WindowsQTLib

on:
  workflow_dispatch:
  
env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}\build'



jobs:
  build-qt-lib:
    name: Build
    runs-on: windows-latest

    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v4

      - name: Configure CMake
        run: echo ${{ env.build }}
      - run: cmake --version
      - run: dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK"
      - run: dir "C:\Program Files (x86)\Windows Kits\10"
      - run: md ${{ env.build }}
      - run: echo hello > ${{ env.build }}\world.txt
      - uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: ${{ env.build }}\world.txt
            compression-level: 9


