# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: WindowsQTLib

on:
  workflow_dispatch:
  
env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}\build'
  


jobs:
  build-qt-lib:
    name: Build
    runs-on: windows-latest

    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v4

      - name: Configure CMake
        run: echo ${{ env.build }}
      - run: ps
      - run: dir "C:\"
      - run: dir "C:\Program Files (x86)\Windows Kits\10\bin"
      - run: md ${{ env.build }}
      - run: ps > ${{ env.build }}\world.txt
      - run: tree "D:\"> ${{ env.build }}\world.txt
      - uses: actions/upload-artifact@v4
        with:
            name: output
            path: ${{ env.build }}\world.txt
            compression-level: 9
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Test Release
            - First Change
            - Second Change
     
      - name: Upload Artifact to Release
        id: upload_artifact
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.build }}/output.zip
          asset_name: output.zip
          asset_content_type: application/zip


